development:
  adapter: mysql2
  database: bwi_store_development
  encoding: unicode
  username: chris
  password: ""

test:
  adapter: mysql2
  database: bwi_store_test
  encoding: unicode
  username: chris
  password: ""

